# config_cpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-highmem-2
   replicaCount: 1
   containerSpec:
      imageUri: eu.gcr.io/aslalphabet-374510/trainer:latest
      env:
      - name: WANDB_API_KEY
        value: "def55c27ab4c0ae01a92a8130377492038a4897c"
      - name: EXP
        value: "experiment=exp1"
