# builds an image when pushing code and pushes it to gcp

steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-f', 'docker/trainer_cloud.dockerfile', '-t', 'eu.gcr.io/aslalphabet-374510/trainer', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'eu.gcr.io/aslalphabet-374510/trainer']
