name: MLOPS_project
channels:
  - defaults
dependencies:
  - pip:
      - aiohttp==3.8.3
      - aiohttp-retry==2.8.3
      - aiosignal==1.3.1
      - alabaster==0.7.12
      - amqp==5.1.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - asyncssh==2.13.0
      - atpublic==3.1.1
      - attrs==22.2.0
      - awscli==1.16.201
      - babel==2.11.0
      - billiard==3.6.4.0
      - botocore==1.12.191
      - cachetools==5.2.1
      - celery==5.2.7
      - cffi==1.15.1
      - charset-normalizer==2.1.1
      - click==8.1.3
      - click-didyoumean==0.3.0
      - click-plugins==1.1.1
      - click-repl==0.2.0
      - colorama==0.3.9
      - commonmark==0.9.1
      - configobj==5.0.6
      - contourpy==1.0.6
      - coverage==7.0.5
      - cryptography==39.0.0
      - cycler==0.11.0
      - decorator==5.1.1
      - dictdiffer==0.9.0
      - diskcache==5.4.0
      - distro==1.8.0
      - docutils==0.19
      - dpath==2.1.4
      - dulwich==0.20.50
      - dvc==2.41.1
      - dvc-data==0.29.0
      - dvc-gdrive==2.19.1
      - dvc-gs==2.20.0
      - dvc-http==2.30.0
      - dvc-objects==0.14.1
      - dvc-render==0.0.17
      - dvc-studio-client==0.3.0
      - dvc-task==0.1.9
      - dvclive==1.3.2
      - filelock==3.9.0
      - flake8==6.0.0
      - flatten-dict==0.4.2
      - flufl-lock==7.1.1
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2022.11.0
      - funcy==1.17
      - future==0.18.2
      - gcsfs==2022.11.0
      - gitdb==4.0.10
      - gitpython==3.1.30
      - google-api-core==2.11.0
      - google-api-python-client==2.72.0
      - google-auth==2.16.0
      - google-auth-httplib2==0.1.0
      - google-auth-oauthlib==0.8.0
      - google-cloud-core==2.3.2
      - google-cloud-storage==2.7.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.4.0
      - googleapis-common-protos==1.58.0
      - grandalf==0.6
      - httplib2==0.21.0
      - hydra-core==1.3.1
      - idna==3.4
      - imagesize==1.4.1
      - iterative-telemetry==0.0.6
      - jinja2==3.1.2
      - jmespath==0.10.0
      - kiwisolver==1.4.4
      - kombu==5.2.4
      - markupsafe==2.1.1
      - matplotlib==3.6.3
      - mccabe==0.7.0
      - multidict==6.0.4
      - nanotime==0.5.2
      - networkx==3.0
      - numpy==1.24.1
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - packaging==23.0
      - pathspec==0.9.0
      - pillow==9.4.0
      - prompt-toolkit==3.0.36
      - protobuf==4.21.12
      - psutil==5.9.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycodestyle==2.10.0
      - pycparser==2.21
      - pydot==1.4.2
      - pydrive2==1.15.0
      - pyflakes==3.0.1
      - pygit2==1.11.1
      - pygments==2.14.0
      - pygtrie==2.5.0
      - pyopenssl==23.0.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-dotenv==0.21.0
      - pytz==2022.7
      - pyyaml==5.1
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rich==13.0.1
      - rsa==3.4.2
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - s3transfer==0.2.1
      - scmrepo==0.1.5
      - shortuuid==1.0.11
      - shtab==1.5.8
      - six==1.16.0
      - smmap==5.0.0
      - snowballstemmer==2.2.0
      - sphinx==6.1.3
      - sphinxcontrib-applehelp==1.0.3
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - tabulate==0.9.0
      - tomlkit==0.11.6
      - torch==1.13.1
      - tqdm==4.64.1
      - typing-extensions==4.4.0
      - uritemplate==4.1.1
      - urllib3==1.25.11
      - vine==5.0.0
      - voluptuous==0.13.1
      - wcwidth==0.2.5
      - yarl==1.8.2
      - zc-lockfile==2.0
